"""initial_schema

Revision ID: d32b245c800d
Revises:
Create Date: 2026-07-28 23:06:36.424801

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d32b245c800d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # 启用 pg_trgm 扩展以支持消息全文模糊搜索
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False, comment="人类可读的项目名称"),
        sa.Column(
            "root_path",
            sa.String(length=4096),
            nullable=False,
            comment="受信任的项目根目录绝对路径",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="项目简要描述"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "project_id", sa.UUID(), nullable=False, comment="所属项目，删除项目时级联删除 Agent"
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Agent 显示名称"),
        sa.Column("agent_type", sa.String(length=50), nullable=False, comment="Agent 平台类型"),
        sa.Column(
            "capabilities",
            postgresql.ARRAY(sa.String(length=50)),
            nullable=True,
            comment="Agent 能力列表，如 ['code_generation', 'testing']",
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="启用/停用状态"),
        sa.Column(
            "adapter_config_ref",
            sa.String(length=1024),
            nullable=True,
            comment="适配器配置引用（仅保存引用名，不保存明文凭据）",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_agents_project_name"),
    )
    op.create_index(op.f("ix_agents_project_id"), "agents", ["project_id"], unique=False)
    op.create_index("ix_agents_status_type", "agents", ["status", "agent_type"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "project_id", sa.UUID(), nullable=False, comment="所属项目，删除项目时级联删除会话"
        ),
        sa.Column("title", sa.String(length=500), nullable=True, comment="会话标题（可为空）"),
        sa.Column("conversation_type", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_project_id"), "conversations", ["project_id"], unique=False
    )
    op.create_index(
        "ix_conversations_project_updated",
        "conversations",
        ["project_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False, comment="冗余项目 ID，用于快速隔离查询"),
        sa.Column("parent_message_id", sa.UUID(), nullable=True, comment="父消息 ID，用于消息线程"),
        sa.Column("role", sa.String(length=20), nullable=False, comment="消息角色"),
        sa.Column(
            "agent_id", sa.UUID(), nullable=True, comment="发送消息的 Agent（仅 role=agent 时有值）"
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="消息正文"),
        sa.Column(
            "content_type",
            sa.String(length=50),
            nullable=False,
            comment="内容类型：text / markdown / html",
        ),
        sa.Column("sequence", sa.Integer(), nullable=False, comment="会话内单调递增序号"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name="uq_messages_conversation_sequence"
        ),
    )
    op.create_index(op.f("ix_messages_agent_id"), "messages", ["agent_id"], unique=False)
    op.create_index(
        "ix_messages_content_trgm",
        "messages",
        ["content"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(
        "ix_messages_project_created", "messages", ["project_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_messages_project_id"), "messages", ["project_id"], unique=False)
    op.create_table(
        "agent_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False, comment="冗余项目 ID，用于快速隔离查询"),
        sa.Column("message_id", sa.UUID(), nullable=False, comment="触发本次执行的消息"),
        sa.Column("agent_id", sa.UUID(), nullable=False, comment="被调用的 Agent"),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False, comment="执行内事件单调递增序号"),
        sa.Column("error_code", sa.String(length=100), nullable=True, comment="稳定错误码"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="安全脱敏后的错误描述"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_executions_agent_created",
        "agent_executions",
        ["agent_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_executions_agent_id"), "agent_executions", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_executions_conversation_id"),
        "agent_executions",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_executions_project_id"), "agent_executions", ["project_id"], unique=False
    )
    op.create_index(
        "ix_agent_executions_project_status",
        "agent_executions",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=50), nullable=False, comment="待审批的动作类型"),
        sa.Column("summary", sa.Text(), nullable=False, comment="动作摘要"),
        sa.Column(
            "content_hash",
            sa.String(length=128),
            nullable=False,
            comment="动作内容哈希，变更后原审批失效",
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="审批状态"),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True, comment="决定时间"),
        sa.Column("decided_by", sa.String(length=255), nullable=True, comment="决定者标识"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["execution_id"], ["agent_executions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_approvals_execution_id"), "approvals", ["execution_id"], unique=False)
    op.create_index(
        "ix_approvals_execution_status", "approvals", ["execution_id", "status"], unique=False
    )
    op.create_index(op.f("ix_approvals_project_id"), "approvals", ["project_id"], unique=False)
    op.create_index(
        "ix_approvals_project_status", "approvals", ["project_id", "status"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False, comment="产生此产出物的执行"),
        sa.Column("artifact_type", sa.String(length=50), nullable=False, comment="产出物类型"),
        sa.Column(
            "relative_path",
            sa.String(length=4096),
            nullable=False,
            comment="相对于项目根目录的路径",
        ),
        sa.Column(
            "content_hash", sa.String(length=128), nullable=False, comment="内容哈希（SHA-256）"
        ),
        sa.Column("size", sa.BigInteger(), nullable=False, comment="文件大小（字节）"),
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="扩展元数据",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["execution_id"], ["agent_executions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_artifacts_execution_id"), "artifacts", ["execution_id"], unique=False)
    op.create_index(
        "ix_artifacts_execution_type", "artifacts", ["execution_id", "artifact_type"], unique=False
    )
    op.create_index(op.f("ix_artifacts_project_id"), "artifacts", ["project_id"], unique=False)
    op.create_index(
        "ix_artifacts_project_type", "artifacts", ["project_id", "artifact_type"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("parent_task_id", sa.UUID(), nullable=True, comment="父任务 ID，用于构建任务树"),
        sa.Column("title", sa.String(length=500), nullable=False, comment="任务标题"),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["execution_id"], ["agent_executions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_agent_id"), "tasks", ["agent_id"], unique=False)
    op.create_index(op.f("ix_tasks_conversation_id"), "tasks", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_tasks_execution_id"), "tasks", ["execution_id"], unique=False)
    op.create_index(op.f("ix_tasks_project_id"), "tasks", ["project_id"], unique=False)
    op.create_index("ix_tasks_project_status", "tasks", ["project_id", "status"], unique=False)
    op.create_table(
        "usage_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.String(length=50),
            nullable=False,
            comment="事件类型：call / token / duration / result",
        ),
        sa.Column("call_count", sa.Integer(), nullable=False, comment="调用次数"),
        sa.Column(
            "token_count",
            sa.Integer(),
            nullable=True,
            comment="Token 消耗量（不可用时为 NULL，不用 0 代替）",
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True, comment="耗时（毫秒）"),
        sa.Column("success", sa.Boolean(), nullable=True, comment="调用是否成功"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["execution_id"], ["agent_executions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usage_events_agent_id"), "usage_events", ["agent_id"], unique=False)
    op.create_index(
        op.f("ix_usage_events_execution_id"), "usage_events", ["execution_id"], unique=False
    )
    op.create_index(
        "ix_usage_events_execution_time",
        "usage_events",
        ["execution_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_events_project_agent_time",
        "usage_events",
        ["project_id", "agent_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_events_project_id"), "usage_events", ["project_id"], unique=False
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("approval_id", sa.UUID(), nullable=True, comment="关联的审批记录"),
        sa.Column("artifact_id", sa.UUID(), nullable=True, comment="关联的部署产出物"),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("target_url", sa.String(length=2048), nullable=True, comment="部署目标 URL"),
        sa.Column("result_url", sa.String(length=2048), nullable=True, comment="部署结果 URL"),
        sa.Column(
            "error_code", sa.String(length=100), nullable=True, comment="部署失败时的稳定错误码"
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["approval_id"], ["approvals.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["artifact_id"], ["artifacts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deployments_project_id"), "deployments", ["project_id"], unique=False)
    op.create_index(
        "ix_deployments_project_status", "deployments", ["project_id", "status"], unique=False
    )
    op.create_table(
        "task_dependencies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False, comment="依赖方任务"),
        sa.Column("depends_on_task_id", sa.UUID(), nullable=False, comment="被依赖的任务"),
        sa.CheckConstraint("task_id <> depends_on_task_id", name="ck_task_dependencies_no_self"),
        sa.ForeignKeyConstraint(["depends_on_task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "depends_on_task_id", name="uq_task_dependencies_pair"),
    )
    op.create_index(
        op.f("ix_task_dependencies_depends_on_task_id"),
        "task_dependencies",
        ["depends_on_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_dependencies_task_id"), "task_dependencies", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_task_dependencies_task_id"), table_name="task_dependencies")
    op.drop_index(op.f("ix_task_dependencies_depends_on_task_id"), table_name="task_dependencies")
    op.drop_table("task_dependencies")
    op.drop_index("ix_deployments_project_status", table_name="deployments")
    op.drop_index(op.f("ix_deployments_project_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_usage_events_project_id"), table_name="usage_events")
    op.drop_index("ix_usage_events_project_agent_time", table_name="usage_events")
    op.drop_index("ix_usage_events_execution_time", table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_execution_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_agent_id"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index("ix_tasks_project_status", table_name="tasks")
    op.drop_index(op.f("ix_tasks_project_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_execution_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_conversation_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_agent_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_artifacts_project_type", table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_project_id"), table_name="artifacts")
    op.drop_index("ix_artifacts_execution_type", table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_execution_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index("ix_approvals_project_status", table_name="approvals")
    op.drop_index(op.f("ix_approvals_project_id"), table_name="approvals")
    op.drop_index("ix_approvals_execution_status", table_name="approvals")
    op.drop_index(op.f("ix_approvals_execution_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index("ix_agent_executions_project_status", table_name="agent_executions")
    op.drop_index(op.f("ix_agent_executions_project_id"), table_name="agent_executions")
    op.drop_index(op.f("ix_agent_executions_conversation_id"), table_name="agent_executions")
    op.drop_index(op.f("ix_agent_executions_agent_id"), table_name="agent_executions")
    op.drop_index("ix_agent_executions_agent_created", table_name="agent_executions")
    op.drop_table("agent_executions")
    op.drop_index(op.f("ix_messages_project_id"), table_name="messages")
    op.drop_index("ix_messages_project_created", table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_content_trgm", table_name="messages")
    op.drop_index(op.f("ix_messages_agent_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_conversations_project_updated", table_name="conversations")
    op.drop_index(op.f("ix_conversations_project_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_agents_status_type", table_name="agents")
    op.drop_index(op.f("ix_agents_project_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("projects")
    # ### end Alembic commands ###
